### ISSUE TITLE
Crash when using Builders Sigil

### ISSUE THREAD

**Issue by the-vindex** [Alex-hawks/Sanguine-Extras#7]
I've used builder's sigil on the wooden block, and it crashed.
Sanguine Utilities-1.3.1.jar
BloodMagic-1.7.10-1.3.1-7.jar
Sanguimancy-1.7.10-1.1.8-4.jar

[20:44:13] [Server thread/ERROR]: Encountered an unexpected exception
java.lang.NoSuchMethodError: WayofTime.alchemicalWizardry.common.items.EnergyItems.checkAndSetItemOwner(Lnet/minecraft/item/ItemStack;Lnet/minecraft/entity/player/EntityPlayer;)V
	at io.github.alex_hawks.SanguineExtras.common.sigils.ItemBuilding.func_77648_a(ItemBuilding.java:53) ~[ItemBuilding.class:?]
	at net.minecraftforge.common.ForgeHooks.onPlaceItemIntoWorld(ForgeHooks.java:505) ~[ForgeHooks.class:?]
	at net.minecraft.item.ItemStack.func_77943_a(ItemStack.java:128) ~[add.class:?]
	at net.minecraft.server.management.ItemInWorldManager.func_73078_a(ItemInWorldManager.java:389) ~[mx.class:?]
	at net.minecraft.network.NetHandlerPlayServer.func_147346_a(NetHandlerPlayServer.java:556) ~[nh.class:?]
	at net.minecraft.network.play.client.C08PacketPlayerBlockPlacement.func_148833_a(SourceFile:60) ~[jo.class:?]
	at net.minecraft.network.play.client.C08PacketPlayerBlockPlacement.func_148833_a(SourceFile:9) ~[jo.class:?]
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212) ~[ej.class:?]
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:165) ~[nc.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:659) ~[MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547) ~[MinecraftServer.class:?]
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:111) ~[bsx.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685) [?:?]
[20:44:13] [Server thread/ERROR]: This crash report has been saved to: F:\Games\multimc-1.7\instances\MagePack\minecraft\crash-reports\crash-2015-03-22_20.44.13-server.txt
[20:44:13] [Server thread/INFO]: Stopping server
[20:44:13] [Server thread/INFO]: Saving players
[20:44:13] [Server thread/INFO]: Saving worlds
[20:44:13] [Server thread/INFO]: Saving chunks for level 'Creative'/Overworld
[20:44:13] [Netty Client IO #1/INFO] [THAUMCRAFT]: Restoring client configs.
[20:44:13] [Netty Client IO #1/INFO] [MineMenu]: CLIENT: Disconnected from server, enabling all click actions
[20:44:13] [Netty Client IO #1/INFO] [OpenMods]: openmods.network.IdSyncManager.onDisconnect(IdSyncManager.java:124): Disconnected, restoring local data
[20:44:13] [Server thread/INFO]: Saving chunks for level 'Creative'/Nether
[20:44:16] [Client thread/INFO] [journeymap]: Mapping halted in F:\Games\multimc-1.7\instances\MagePack\minecraft\journeymap\data\sp\Creative\DIM0
[20:44:16] [Server thread/INFO]: Saving chunks for level 'Creative'/The End
[20:44:16] [Server thread/INFO]: Saving chunks for level 'Creative'/Spirit World
[20:44:16] [Server thread/INFO]: Saving chunks for level 'Creative'/Torment
[20:44:16] [Server thread/INFO]: Saving chunks for level 'Creative'/The Outer Lands
[20:44:16] [Server thread/INFO] [FML]: Unloading dimension 0
[20:44:16] [Server thread/INFO] [FML]: Unloading dimension -1
[20:44:16] [Server thread/INFO] [FML]: Unloading dimension 1
[20:44:16] [Server thread/INFO] [FML]: Unloading dimension -37
[20:44:16] [Server thread/INFO] [FML]: Unloading dimension -38
[20:44:16] [Server thread/INFO] [FML]: Unloading dimension -42
[20:44:18] [Client thread/FATAL]: Unreported exception thrown!
java.lang.NoSuchMethodError: WayofTime.alchemicalWizardry.common.items.EnergyItems.checkAndSetItemOwner(Lnet/minecraft/item/ItemStack;Lnet/minecraft/entity/player/EntityPlayer;)V
	at io.github.alex_hawks.SanguineExtras.common.sigils.ItemBuilding.func_77648_a(ItemBuilding.java:53) ~[ItemBuilding.class:?]
	at net.minecraft.item.ItemStack.func_77943_a(ItemStack.java:129) ~[add.class:?]
	at net.minecraft.client.multiplayer.PlayerControllerMP.func_78760_a(PlayerControllerMP.java:353) ~[bje.class:?]
	at net.minecraft.client.Minecraft.func_147121_ag(Minecraft.java:1435) ~[bao.class:?]
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1941) ~[bao.class:?]
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:961) ~[bao.class:?]
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:887) [bao.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:148) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.7.0_65]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.7.0_65]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.7.0_65]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.7.0_65]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.11.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.11.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.7.0_65]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.7.0_65]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.7.0_65]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.7.0_65]
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:286) [NewLaunch.jar:?]
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:376) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.listen(EntryPoint.java:165) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.main(EntryPoint.java:54) [NewLaunch.jar:?]
[20:44:18] [Client thread/INFO] [STDOUT]: [net.minecraft.client.Minecraft:func_71377_b:349]: ---- Minecraft Crash Report ----
// Why did you do that?

Time: 3/22/15 8:44 PM
Description: Unexpected error

java.lang.NoSuchMethodError: WayofTime.alchemicalWizardry.common.items.EnergyItems.checkAndSetItemOwner(Lnet/minecraft/item/ItemStack;Lnet/minecraft/entity/player/EntityPlayer;)V
	at io.github.alex_hawks.SanguineExtras.common.sigils.ItemBuilding.func_77648_a(ItemBuilding.java:53)
	at net.minecraft.item.ItemStack.func_77943_a(ItemStack.java:129)
	at net.minecraft.client.multiplayer.PlayerControllerMP.func_78760_a(PlayerControllerMP.java:353)
	at net.minecraft.client.Minecraft.func_147121_ag(Minecraft.java:1435)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1941)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:961)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:887)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:286)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:376)
	at org.multimc.EntryPoint.listen(EntryPoint.java:165)
	at org.multimc.EntryPoint.main(EntryPoint.java:54)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at io.github.alex_hawks.SanguineExtras.common.sigils.ItemBuilding.func_77648_a(ItemBuilding.java:53)
	at net.minecraft.item.ItemStack.func_77943_a(ItemStack.java:129)
	at net.minecraft.client.multiplayer.PlayerControllerMP.func_78760_a(PlayerControllerMP.java:353)
	at net.minecraft.client.Minecraft.func_147121_ag(Minecraft.java:1435)

**Comment by Alex-hawks** [comment]
I need to update my blood magic dev version
